# Generated by Django 2.2.3 on 2019-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender_enum',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 0), ('FEMALE', 1), ('UNIDENTIFIED', 2)], default=2, max_length=100),
        ),
    ]
